FORMAT: 1A
HOST: http://www.google.com

# Ruian HB API
Ruian HB API is a internal API for providing information from internal RUIAN database mirror.

# Group Autocomplete
Autocomplete resources of the Ruian HB API

## City Query [/rest/city{?term}]
### Search cities started by term [GET]
+ Parameters
    + term (required, string, `Pra`) ... City search term

+ Response 200 (application/json)

        [{ 
            "label": "Praha", "value": 1
        }, {
            "label": "Prachatice", "value": 2      
        }]

## City Detail [/rest/city/{id}]
### Get city detail [GET]
+ Parameters
    + id (required, string, `1`) ... City identification

+ Response 200 (application/json)

        {
            "name": "Praha"
        }

## City subquery [/rest/city/{id}/{type}{?term}]
### Search objects related to city, like street, city part etc. [GET]
+ Parameters
    + id (required, string, `1`) ... City identification
    + type (required, string, `street`) ... Related item type
    + term (optional, string, `Mak`) ... City search term

+ Response 200 (application/json)

        [{
            "type": "street", "name": "Makovská"
        }, {
            "type": "street", "name": "Makovského"
        }]
